config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from poll import urls
from polladmin import urls as admin_url
from users import urls as user_url


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin_url, namespace="adminurl")),
    url(r'^poll/', include(urls, namespace="poll")),
    url(r'^users/', include(user_url, namespace="userurl")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name="results"),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name="vote"),
    url(r'^homepage/$', views.homepage, name="homepage"),
    url(r'^searchbox/$', views.search_box, name="search_box"),
    url(r'^verticaltimeline/$', views.vertical_timeline, name="vertical_timeline"),
    url(r'^btndown/$', views.btn_down, name="btn_down"),
    url(r'^mobiledesign/$', views.mobileDesign, name="mobiledesign"),
    url(r'^generateqrcode/(?P<pid>\d+)$', views.GenerateQRCode, name="generateqrcode"),
    url(r'^uploadimg/$', views.upload_image, name="upload_image"),
    url(r'^showimg/$', views.show_img, name="show_img"),
    url(r'^test/$', views.test_url, name="test_url"),
]

polladmin/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView, name="index"),
    url(r'^productinfo$', views.ProductInfoView, name="productinfo"),
    url(r'^testpagechange/$', views.Test_changepage, name="testpagechange"),
    url(r'^testpagechangeone/', views.Test_changepage_one, name="testpagechangeone"),
    url(r'^testpagechangetwo/', views.Test_changepage_two, name="testpagechangetwo"),
    url(r'^datatable/', views.datatable, name="datatable"),
    url(r'^userinfo/$', views.userInfo, name="userInfo"),
]

templates/changepage/itemonepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>one</title>
</head>
<body>
    <div id="containers">
        <div>
            <p>page one</p>
        </div>
        <h2>page one</h2>
    </div>
</body>
</html>

templates/changepage/itemtwopage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>two</title>
</head>
<body>
    <div class="page-wrapper" id="containers">
            <!-- Bread crumb(右侧最上面的标题栏) -->
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-primary">产品信息</h3> </div>
                <div class="col-md-7 align-self-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">主页</a></li>
                        <li class="breadcrumb-item active">产品信息查看(访问路径预留)</li>
                    </ol>
                </div>
            </div>
            <!-- End Bread crumb -->

            <!-- Container fluid  -->
            <div class="container-fluid">
                <!-- Start Page Content -->


                <div class="row bg-white m-l-0 m-r-0 box-shadow ">
                   <!-- <p>这是产品信息</p>  -->
                <!--
                    <!-- column -(原来内容)->
                    <div class="col-lg-8">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Extra Area Chart</h4>
                                <div id="extra-area-chart"></div>
                            </div>
                        </div>
                    </div>
                    <!-- column -(原来内容)->

                    <!-- column -(原来内容)->
                    <div class="col-lg-4">
                        <div class="card">
                            <div class="card-body browser">
                                <p class="f-w-600">iMacs <span class="pull-right">85%</span></p>
                                <div class="progress ">
                                    <div role="progressbar" style="width: 85%; height:8px;" class="progress-bar bg-danger wow animated progress-animated"> <span class="sr-only">60% Complete</span> </div>
                                </div>

                                <p class="m-t-30 f-w-600">iBooks<span class="pull-right">90%</span></p>
                                <div class="progress">
                                    <div role="progressbar" style="width: 90%; height:8px;" class="progress-bar bg-info wow animated progress-animated"> <span class="sr-only">60% Complete</span> </div>
                                </div>

                                <p class="m-t-30 f-w-600">iPhone<span class="pull-right">65%</span></p>
                                <div class="progress">
                                    <div role="progressbar" style="width: 65%; height:8px;" class="progress-bar bg-success wow animated progress-animated"> <span class="sr-only">60% Complete</span> </div>
                                </div>

                                <p class="m-t-30 f-w-600">Samsung<span class="pull-right">65%</span></p>
                                <div class="progress">
                                    <div role="progressbar" style="width: 65%; height:8px;" class="progress-bar bg-warning wow animated progress-animated"> <span class="sr-only">60% Complete</span> </div>
                                </div>

								<p class="m-t-30 f-w-600">android<span class="pull-right">65%</span></p>
                                <div class="progress m-b-30">
                                    <div role="progressbar" style="width: 65%; height:8px;" class="progress-bar bg-success wow animated progress-animated"> <span class="sr-only">60% Complete</span> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- column -(原来内容)->
                -->
                </div>
                <!-- End PAge Content -->
            </div>
            <!-- End Container fluid  -->
            <!-- footer -->
            <footer class="footer"> © 2018 All rights reserved. Template designed by <a href="https://colorlib.com">Colorlib</a></footer>
            <!-- End footer -->
        </div>
</body>
</html>

templates/changepage/mainpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>

    <div>
        <a data-pjax href="{% url 'adminurl:testpagechangeone' %}"> itemone</a>
        <a data-pjax href="{% url 'adminurl:testpagechangetwo' %}"> itemtwo</a>
    </div>
    <div id="container">
    </div>
    <script src="/static/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="/static/js/jquery.pjax.js"></script>
    <script>
        $(document).pjax('a[data-pjax]', '#container', {fragment: "#containers"});

{#        $(function () {#}
{#            $("p[data-pjax]").click(function () {#}
{#                var content = $(this).text();#}
{#                console.log(content);#}
{#                if(content == "itemone"){#}
{#                    $.pjax({url: "{% url 'adminurl:testpagechangeone' %}", container: '#container', fragment: "#container"})#}
{#                }else {#}
{#                    $.pjax({url: "{% url 'adminurl:testpagechangetwo' %}", container: '#container', fragment: "#container"})#}
{#                }#}
{#            });#}
{#        });#}
    </script>
</body>
</html>