config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from poll import urls
from polladmin import urls as admin_url
from users import urls as user_url


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin_url, namespace="adminurl")),
    url(r'^poll/', include(urls, namespace="poll")),
    url(r'^users/', include(user_url, namespace="userurl")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name="results"),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name="vote"),
    url(r'^homepage/$', views.homepage, name="homepage"),
    url(r'^searchbox/$', views.search_box, name="search_box"),
    url(r'^verticaltimeline/$', views.vertical_timeline, name="vertical_timeline"),
    url(r'^btndown/$', views.btn_down, name="btn_down"),
    url(r'^mobiledesign/$', views.mobileDesign, name="mobiledesign"),
    url(r'^generateqrcode/(?P<pid>\d+)$', views.GenerateQRCode, name="generateqrcode"),
    url(r'^uploadimg/$', views.upload_image, name="upload_image"),
    url(r'^showimg/$', views.show_img, name="show_img"),
    url(r'^test/$', views.test_url, name="test_url"),
]

polladmin/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView, name="index"),
    url(r'^productinfo$', views.ProductInfoView, name="productinfo"),
    url(r'^testpagechange/$', views.Test_changepage, name="testpagechange"),
    url(r'^testpagechangeone/', views.Test_changepage_one, name="testpagechangeone"),
    url(r'^testpagechangetwo/', views.Test_changepage_two, name="testpagechangetwo"),
    url(r'^datatable/', views.datatable, name="datatable"),
    url(r'^userinfo/$', views.userInfo, name="userInfo"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.min.css"/>
    <script src="/static/js/bootstrap.min.js"></script>
</head>
<body>
    {% include "navigation.html" %}

    {% block content %}{% endblock %}
</body>
</html>

templates/btn_down.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Grayscale - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->

    <link href="/static/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>


    <!-- Custom styles for this template -->
    <link href="/static/css/grayscale.min.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#download">Download</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Intro Header -->
    <header class="masthead">
      <div class="intro-body">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h1 class="brand-heading">Grayscale</h1>
              <p class="intro-text">A free, responsive, one page Bootstrap theme.
                <br>Created by Start Bootstrap.</p>
              <a class="btn btn-circle" id="test_scroll">
                <i class="fa fa-angle-double-down"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- About Section -->
    <section id="about" class="content-section text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>About Grayscale</h2>
            <p>Grayscale is a free Bootstrap theme created by Start Bootstrap. It can be yours right now, simply download the template on
              <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
            <p>This theme features stock photos by
              <a href="http://gratisography.com/">Gratisography</a>
              along with a custom Google Maps skin courtesy of
              <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
            <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with SASS and LESS files for easy customization!</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="download-section content-section text-center">
      <div class="container">
        <div class="col-lg-8 mx-auto">
          <h2>Download Grayscale</h2>
          <p>You can download Grayscale for free on the preview page at Start Bootstrap.</p>
          <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Download Page</a>
        </div>
      </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="content-section text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Contact Start Bootstrap</h2>
            <p>Feel free to leave us a comment on the
              <a href="http://startbootstrap.com/template-overviews/grayscale/">Grayscale template overview page</a>
              on Start Bootstrap to give some feedback about this theme!</p>
            <ul class="list-inline banner-social-buttons">
              <li class="list-inline-item">
                <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg">
                  <i class="fa fa-twitter fa-fw"></i>
                  <span class="network-name">Twitter</span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/BlackrockDigital/startbootstrap" class="btn btn-default btn-lg">
                  <i class="fa fa-github fa-fw"></i>
                  <span class="network-name">Github</span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg">
                  <i class="fa fa-google-plus fa-fw"></i>
                  <span class="network-name">Google+</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <!-- Map Section -->
    <div id="map"></div>

    <!-- Footer -->
    <footer>
      <div class="container text-center">
        <p>Copyright &copy; Your Website 2018</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="/static/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="/static/js/vendor/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="/static/js/jquery.easing.min.js"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

    <!-- Custom scripts for this template -->
    <script src="/static/js/grayscale.min.js"></script>

  <script>
      $(function () {
          $("#test_scroll").click(function () {
               document.getElementById("about").scrollIntoView({behavior: "smooth"});
               console.log("scroll")
          });
      });
  </script>

  </body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/mobile_design.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Color theme for statusbar -->
    <meta name="theme-color" content="#2196f3">
    <!-- Your app title -->
    <title>My App</title>
    <!-- Path to Framework7 Library CSS, Material Theme -->

    <link rel="stylesheet" href="/static/css/framework7.md.min.css">
{#    <link rel="stylesheet" href="/static/css/framework7.material.colors.min.css"/>#}
    <!-- Path to Framework7 color related styles, Material Theme -->
{#    <link rel="stylesheet" href="/static/css/framework7.material.colors.min.css">#}
    <!-- Path to your custom app styles-->
{#    <link rel="stylesheet" href="path/to/my-app.css">#}
  </head>
  <body>
    <!-- Views -->
    <div class="views">
      <!-- Your main view, should have "view-main" class -->
      <div class="view view-main">
        <!-- Pages container, because we use fixed navbar and toolbar, it has additional appropriate classes-->
        <div class="pages navbar-fixed toolbar-fixed">
          <!-- Page, "data-page" contains page name -->
          <div data-page="index" class="page">

            <!-- Top Navbar. In Material theme it should be inside of the page-->
            <div class="navbar">
              <div class="navbar-inner">
                <div class="title">Awesome App</div>
              </div>
            </div>

            <!-- Scrollable page content -->
              <div class="page-content">
                  <div class="timeline">
                      <div class="timeline-item">
                          <div class="timeline-item-date">21
                              <small>DEC</small>
                          </div>
                          <div class="timeline-item-divider"></div>
                          <div class="timeline-item-content">
                              <div class="timeline-item-inner">
                                  <div class="timeline-item-time">12:30</div>
                                  <div class="timeline-item-title">Title</div>
                                  <div class="timeline-item-subtitle">Subtitle</div>
                                  <div class="timeline-item-text">Text</div>
                              </div>
                          </div>
                      </div>
                      <div class="timeline-item">
                          <div class="timeline-item-date">20
                              <small>DEC</small>
                          </div>
                          <div class="timeline-item-divider"></div>
                          <div class="timeline-item-content">
                              <div class="timeline-item-inner">
                                  <div class="timeline-item-time">11:30</div>
                                  <div class="timeline-item-title">我是标题</div>
                                  <div class="timeline-item-subtitle">子标题是也</div>
                                  <div class="timeline-item-text">我是内容，内容，内容，内容</div>
                              </div>
                          </div>
                      </div>

                      <div class="timeline-item">
                          <div class="timeline-item-date">19
                              <small>DEC</small>
                          </div>
                          <div class="timeline-item-divider"></div>
                          <div class="timeline-item-content">
                              <div class="timeline-item-inner">
                                  <div class="timeline-item-time">11:30</div>
                                  <div class="timeline-item-title">我是标题</div>
                                  <div class="timeline-item-subtitle">子标题是也</div>
                                  <div class="timeline-item-text">我是内容，内容，内容，内容</div>
                              </div>
                          </div>
                      </div>
                      <div class="timeline-item">
                          <div class="timeline-item-date">18
                              <small>DEC</small>
                          </div>
                          <div class="timeline-item-divider"></div>
                          <div class="timeline-item-content">
                              <div class="timeline-item-inner">
                                  <div class="timeline-item-time">11:30</div>
                                  <div class="timeline-item-title">我是标题</div>
                                  <div class="timeline-item-subtitle">子标题是也</div>
                                  <div class="timeline-item-text">我是内容，内容，内容，内容</div>
                              </div>
                          </div>
                      </div>
                  </div>

              <!-- Bottom Toolbar. In Material theme it should be inside of the page-->
            <div class="toolbar toolbar-bottom-md">
              <div class="toolbar-inner">
                <!-- Toolbar links -->
                <a href="#" class="link">Link 1</a>
                <a href="#" class="link">Link 2</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Path to Framework7 Library JS-->
    <script type="text/javascript" src="/static/js/framework7.min.js"></script>
    <!-- Path to your app js-->
    <script type="text/javascript" src="/static/js/my-app.js"></script>
  </body>
</html>

templates/mobile_design_sui.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>石斑鱼后台管理</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="//g.alicdn.com/msui/sm/0.6.2/css/sm.min.css">

  </head>
  <body>
    <!-- page集合的容器，里面放多个平行的.page，其他.page作为内联页面由路由控制展示 -->
    <div class="page-group">
        <!-- 单个page ,第一个.page默认被展示-->
        <div class="page">
            <!-- 标题栏 -->
            <header class="bar bar-nav">
                <h1 class="title">标题</h1>
            </header>

            <!-- 工具栏 -->
            <nav class="bar bar-tab ripple">
                <a class="tab-item external active" href="#">
                    <span class="icon icon-home"></span>
                    <span class="tab-label">首页</span>
                </a>
                <a class="tab-item external" href="#">
                    <span class="icon icon-star"></span>
                    <span class="tab-label">入料</span>
                </a>
                <a class="tab-item external" href="#">
                    <span class="icon icon-star"></span>
                    <span class="tab-label">转移</span>
                </a>
                <a class="tab-item external" href="#">
                    <span class="icon icon-star"></span>
                    <span class="tab-label">领料</span>
                </a>
                <a class="tab-item external" href="#">
                    <span class="icon icon-settings"></span>
                    <span class="tab-label">设置</span>
                </a>
            </nav>

            <!-- 这里是页面内容区 -->
            <div class="content">
                <div class="content-block">
                    我是content
                </div>
            </div>
        </div>
        <!-- 其他的单个page内联页（如果有） -->
        <div class="page"></div>
    </div>

    <script type='text/javascript' src='//g.alicdn.com/sj/lib/zepto/zepto.min.js' charset='utf-8'></script>
    <script type='text/javascript' src='//g.alicdn.com/msui/sm/0.6.2/js/sm.min.js' charset='utf-8'></script>

  </body>
</html>

templates/mydatatable.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/static/polladmin/images/favicon.png">
    <title>石斑鱼后台管理系统</title>
    <!-- Bootstrap Core CSS -->
    <link href="/static/polladmin/css/lib/bootstrap/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/static/polladmin/css/lib/data-table/bootstrap-table.css" rel="stylesheet">

</head>

<body class="fix-header fix-sidebar">
    <!-- Main wrapper  -->
    <div id="main-wrapper">
        <!-- Page wrapper  -->
        {% block rightside-page-content %}
        <div class="page-wrapper" id="rightside-page-wrapper">
            <!-- Container fluid  -->
            <div class="container-fluid">
                <!-- Start Page Content -->

                 <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Data Table</h4>
                                <h6 class="card-subtitle">Data table example</h6>
                                <div class="table-responsive m-t-40">
                                    <div id="toolbar">
                                      <button id="add-user" class="btn btn-danger">
                                        <a class="fa fa-remove" href="#"></a> 添加
                                      </button>
                                      <button id="remove" class="btn btn-danger" disabled>
                                        <i class="fa fa-remove"></i> 删除
                                      </button>
                                    </div>
                                    <table data-toggle="table"
                                           data-toolbar="#toolbar"
                                           data-search="true"
                                           data-minimum-count-columns="2"
                                           data-pagination="true"
                                           data-id-field="username"
                                           data-click-to-select="true"
                                           data-page-list="[10, 25, 50, 100]"
                                           data-side-pagination="server"
                                           data-height="100%"
                                           data-url="{% url 'adminurl:userInfo' %}">

                                        <thead>
                                            <tr>
                                                <th data-field="state" data-checkbox="true"></th>
                                                <th data-field="username" data-sortable="true" data-align="center">用户名</th>
                                                <th data-field="employeeID" data-sortable="true"  data-align="center">员工号</th>
                                                <th data-field="is_staff" data-align="center">是否为普通员工</th>
                                                <th data-field="is_superuser" data-align="center">是否为管理员</th>
                                                <th data-field="operate" data-align="center">操作</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- End PAge Content -->
            </div>
            <!-- End Container fluid  -->
            <!-- footer -->
            <footer class="footer"> © 2018 All rights reserved. Template designed by <a href="https://colorlib.com">Colorlib</a></footer>
            <!-- End footer -->
        </div>
        {% endblock %}
        <!-- End Page wrapper  -->


    </div>
    <!-- End Wrapper -->
    <!-- All Jquery -->
    <script src="/static/polladmin/js/lib/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="/static/polladmin/js/lib/bootstrap/js/popper.min.js"></script>
    <script src="/static/polladmin/js/lib/bootstrap/js/bootstrap.min.js"></script>

    <script src="/static/polladmin/js/lib/datatables/bootstrap-table.js"></script>
    <script src="/static/polladmin/js/bootstrap-table-zh-CN.js"></script>
</body>

</html>

templates/navigation.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">石斑鱼溯源</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

templates/searchbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>searchbox</title>
    <link rel="stylesheet" href="/static/css/search_box.css"/>

</head>
<body>
<form class="form-wrapper cf">
    <input type="text" placeholder="输入产品编号" required>
    <button type="submit">Search</button>
</form>

 <h1>{{ test }}</h1>
</body>
</html>

templates/showImg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图片展示</title>
</head>
<body>
    {% for item in imgs %}
        <img src="{{ item.img.url }}"><br/>
    {% endfor %}
</body>
</html>

templates/year_archive.html
{% extends "base.html" %}

{% block title %}
    Articles for {{ year }}
{% endblock %}

{% block content %}
    <h1>Articles for {{ year }}</h1>

    {% for article in article_list %}
        <p>{{ article.headline }}</p>
        <p>By {{ article.reporter.full_name }}</p>
        <p>Published {{ article.pub_data|data:"F j, Y" }}</p>
    {% endfor %}


{% endblock %}