config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from poll import urls
from polladmin import urls as admin_url
from users import urls as user_url


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin_url, namespace="adminurl")),
    url(r'^poll/', include(urls, namespace="poll")),
    url(r'^users/', include(user_url, namespace="userurl")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name="results"),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name="vote"),
    url(r'^homepage/$', views.homepage, name="homepage"),
    url(r'^searchbox/$', views.search_box, name="search_box"),
    url(r'^verticaltimeline/$', views.vertical_timeline, name="vertical_timeline"),
    url(r'^btndown/$', views.btn_down, name="btn_down"),
    url(r'^mobiledesign/$', views.mobileDesign, name="mobiledesign"),
    url(r'^generateqrcode/(?P<pid>\d+)$', views.GenerateQRCode, name="generateqrcode"),
    url(r'^uploadimg/$', views.upload_image, name="upload_image"),
    url(r'^showimg/$', views.show_img, name="show_img"),
    url(r'^test/$', views.test_url, name="test_url"),
]

users/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    # url(r'^login/', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', logout, {'template_name': 'users/logout.html'}, name='logout'),
]

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if form.errors %}
<p>
    用户名或密码错误
</p>
{% endif %}
<form action="{% url 'userurl:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username"/>
    <input type="password" name="password"/>
    <input type="submit" value="登录"/>
    <input type="hidden" name="next" value="{{ next }}"/>
</form>
</body>
</html>

templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>